MyMeetUp.Web/Areas/Admin/Controllers/EventsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyMeetUp.Web.Data;
using MyMeetUp.Web.Models;
using System.Linq;
using System.Threading.Tasks;

namespace MyMeetUp.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = RolesData.Administrator)]
    public class EventsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EventsController(ApplicationDbContext context) {
            _context = context;
        }

        // GET: Admin/Events
        public async Task<IActionResult> Index() {
            var applicationDbContext = _context.Events.Include(ec => ec.EventCategory).Include(g => g.Group);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Admin/Events/Details/5
        public async Task<IActionResult> Details(int? id) {
            if (id == null) {
                return NotFound();
            }

            var @event = await _context.Events
                .Include(ec => ec.EventCategory)
                .Include(g => g.Group)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@event == null) {
                return NotFound();
            }

            return View(@event);
        }

        // GET: Admin/Events/Create
        public IActionResult Create() {
            ViewData["EventCategoryId"] = new SelectList(_context.EventCategories, "Id", "Name");
            ViewData["GroupId"] = new SelectList(_context.Groups, "Id", "Name");
            return View();
        }

        // POST: Admin/Events/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,Description,Address,City,Country,FechaHora,GroupId,EventCategoryId,Id")] Event @event) {
            if (ModelState.IsValid) {
                _context.Add(@event);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EventCategoryId"] = new SelectList(_context.EventCategories, "Id", "Name", @event.EventCategoryId);
            ViewData["GroupId"] = new SelectList(_context.Groups, "Id", "Name", @event.GroupId);
            return View(@event);
        }

        // GET: Admin/Events/Edit/5
        public async Task<IActionResult> Edit(int? id) {
            if (id == null) {
                return NotFound();
            }

            var @event = await _context.Events.FindAsync(id);
            if (@event == null) {
                return NotFound();
            }
            ViewData["EventCategoryId"] = new SelectList(_context.EventCategories, "Id", "Name", @event.EventCategoryId);
            ViewData["GroupId"] = new SelectList(_context.Groups, "Id", "Name", @event.GroupId);
            return View(@event);
        }

        // POST: Admin/Events/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Title,Description,Address,City,Country,FechaHora,GroupId,EventCategoryId,Id")] Event @event) {
            if (id != @event.Id) {
                return NotFound();
            }

            if (ModelState.IsValid) {
                try {
                    _context.Update(@event);
                    await _context.SaveChangesAsync();
                } catch (DbUpdateConcurrencyException) {
                    if (!EventExists(@event.Id)) {
                        return NotFound();
                    }
                    else {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EventCategoryId"] = new SelectList(_context.EventCategories, "Id", "Name", @event.EventCategoryId);
            ViewData["GroupId"] = new SelectList(_context.Groups, "Id", "Name", @event.GroupId);
            return View(@event);
        }

        // GET: Admin/Events/Delete/5
        public async Task<IActionResult> Delete(int? id) {
            if (id == null) {
                return NotFound();
            }

            var @event = await _context.Events
                .Include(ec => ec.EventCategory)
                .Include(g => g.Group)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@event == null) {
                return NotFound();
            }

            return View(@event);
        }

        // POST: Admin/Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id) {
            var @event = await _context.Events.FindAsync(id);
            _context.Events.Remove(@event);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventExists(int id) {
            return _context.Events.Any(e => e.Id == id);
        }
    }
}

MyMeetUp.Web/Controllers/GroupsController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using MyMeetUp.Web.Data;
using MyMeetUp.Web.Models;
using MyMeetUp.Web.Services.Interfaces;
using MyMeetUp.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ApplicationInsights;
using Microsoft.WindowsAzure.Storage.Blob;

namespace MyMeetUp.Web.Controllers
{
    public class GroupsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger _logger;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IQueueService _eventQueueService;
        private readonly IAzureBlobManager _azureBlobManager;
        private readonly IWebHostEnvironment _hostingEnvirontment;
        private TelemetryClient _telemetryClient;

        public GroupsController(ApplicationDbContext context, 
                                SignInManager<ApplicationUser> signInManager, 
                                UserManager<ApplicationUser> userManager, 
                                ILogger<GroupsController> logger,
                                IQueueService eventQueueService,
                                IAzureBlobManager azureBlobManager,
                                IWebHostEnvironment environment,
                                TelemetryClient telemetry) {
            _context = context;
            _signInManager = signInManager;
            _userManager = userManager;
            _logger = logger;
            _eventQueueService = eventQueueService;
            _azureBlobManager = azureBlobManager;
            _hostingEnvirontment = environment;
            _telemetryClient = telemetry;
        }

        // GET: Groups
        [Route("Groups/Index/{userId}")]
        public async Task<IActionResult> Index(string userId) {
            GroupIndexViewModel model = new GroupIndexViewModel();
            model.UserId = userId;

            if (userId != null && userId != "") {
                model.AllGroups = await _context.GroupMembers
                    .Include(gm => gm.Group)
                    .Where(gm => gm.ApplicationUserId == userId)
                    .Select(gm => gm.Group)
                    .ToListAsync();

                model.ActualUserAsGroupCoordinator = await _context.GroupMembers
                    .Include(gmp => gmp.GroupMemberProfile)
                    .Where(gm => gm.ApplicationUserId == userId && gm.GroupMemberProfile.Name == GroupMemberProfilesData.Coordinator)
                    .Select(gm => gm.GroupId)
                    .ToListAsync();

                model.ActualUserAsGroupMember = await _context.GroupMembers
                    .Include(gmp => gmp.GroupMemberProfile)
                    .Where(gm => gm.ApplicationUserId == userId && gm.GroupMemberProfile.Name == GroupMemberProfilesData.Member)
                    .Select(gm => gm.GroupId)
                    .ToListAsync();

                await GetGroupCategories(model);

                return View(model);
            }
            else {
                model.AllGroups = await _context.Groups.ToListAsync();
                model.ActualUserAsGroupCoordinator = null;
                model.ActualUserAsGroupMember = null;
                await GetGroupCategories(model);
                return View(model);
            }
            
        }

        private async Task GetGroupCategories(GroupIndexViewModel model) {
            model.GroupCategories = new Dictionary<int, List<string>>();
            foreach (Group group in model.AllGroups) {
                List<string> groupCategories = await _context.Group_GroupCategories
                                                .Include(ggc => ggc.GroupCategory)
                                                .Where(ggc => ggc.GroupId == group.Id)
                                                .Select(ggc => ggc.GroupCategory.Name)
                                                .ToListAsync();
                model.GroupCategories.Add(group.Id, groupCategories);
            }
        }

        // GET: Groups/Details/5
        public async Task<IActionResult> Details(int? id) {
            if (id == null) {
                _logger.LogWarning($"Groups/Details: id {id} no válido..");
                return NotFound();
            }

            var groupSelected = await _context.Groups
                .FirstOrDefaultAsync(m => m.Id == id);
            if (groupSelected == null) {
                _logger.LogWarning($"Groups/Details: Id grupo = {id} no encontrado..");
                return NotFound();
            }

            var groupEventsSelected = await _context.Events.Where(e => e.GroupId == groupSelected.Id).OrderByDescending(e => e.FechaHora).ToListAsync();
            _logger.LogInformation($"Groups/Details: Id grupo = {id} Eventos: {groupEventsSelected.Count}");

            int numGroupMembers = _context.GroupMembers.Where(gm => gm.GroupId == groupSelected.Id).Count();
            _logger.LogInformation($"Groups/Details: Id grupo = {id} Miembros: {numGroupMembers}");

            List<IListBlobItem> blobList = await _azureBlobManager.ListBlobsHierarchicalListingAsync(id + "/groupimage/");
            string urlBlobGroupImage = blobList.Count > 0 ? blobList[0].StorageUri.PrimaryUri.ToString() : "";
            _logger.LogInformation($"Groups/Details: Id grupo = {id} Blob URL: {urlBlobGroupImage}");

            var groupDetailsViewModel = new GroupDetailsViewModel
            {
                GroupInfo = groupSelected,
                GroupProfileImagePath = urlBlobGroupImage,
                GroupEvents = groupEventsSelected,
                MembersTotalNumber = numGroupMembers
            };

            var dictionay = new Dictionary<string, string>();
            dictionay.Add("Group Details", groupSelected.Name);
            _telemetryClient.TrackEvent("UserInteraction", dictionay);

            return View(groupDetailsViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RegisterNewMember(string userId, int groupId) {
            try {

                GroupMemberProfile memberProfile = await _context.GroupMemberProfiles.FirstOrDefaultAsync(gmp => gmp.Name == GroupMemberProfilesData.Member);

                GroupMembers newGroupMember = new GroupMembers
                {
                    GroupId = groupId,
                    ApplicationUserId = userId,
                    GroupMemberProfileId = memberProfile.Id
                };

                _context.GroupMembers.Add(newGroupMember);
                await _context.SaveChangesAsync();

                string message = $"{EventQueueMessages.NEW_GROUP_MEMBER};{newGroupMember.GroupId};{newGroupMember.ApplicationUserId}";
                await _eventQueueService.SendMessageAsync(message);
                var dictionay = new Dictionary<string, string>();
                dictionay.Add("Queue Message", message);
                _telemetryClient.TrackEvent("UserInteraction", dictionay);

            } catch (Exception e) {
                _logger.LogCritical($"EXCEPCIÓN: {e.Message}");
                return Json(new { success = false });
            }

            return Json(new { success = true });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UnregisterMember(string userId, int groupId) {
            try {

                List<GroupMembers> groupMemberProfiles = await _context.GroupMembers.Where(gm => gm.GroupId == groupId && gm.ApplicationUserId == userId).ToListAsync();
                foreach (GroupMembers groupMember in groupMemberProfiles) {
                    _context.Remove(groupMember);
                }
                await _context.SaveChangesAsync();
            } catch (Exception e) {
                _logger.LogCritical($"EXCEPCIÓN: {e.Message}");
                return Json(new { success = false });
            }

            var dictionay = new Dictionary<string, string>();
            dictionay.Add("Unregisted Group Member", $"userId: {userId}");
            _telemetryClient.TrackEvent("UserInteraction", dictionay);

            return Json(new { success = true });
        }

        // GET: Groups/Create
        [HttpGet]
        public async Task<IActionResult> Create() {
            GroupCreateViewModel model = new GroupCreateViewModel
            {
                GroupCategoriesSelected = new List<int> { 1 },
                GroupCategoriesList =  GetGroupCategories()
            };
            return View(model);
        }

        private SelectList GetGroupCategories() {
            return new SelectList(_context.GroupCategories.OrderBy(gc => gc.Id), "Id", "Name");
        }

        
        // POST: Groups/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(GroupCreateViewModel group) {
            int newGroupId;
            string userSignedIn;

            if (!ModelState.IsValid) {
                return View(group);
            }
            using (var dbContextTransaction = _context.Database.BeginTransaction()) {
                try {
                    await CreatesNewGroup(group);
                    newGroupId = await CreatesGroupCategories(group);
                    userSignedIn = await CreatesCoordinatorUserByDefault(newGroupId);

                    await _context.SaveChangesAsync();
                    dbContextTransaction.Commit();

                    await _azureBlobManager.UploadFile(group.GroupImage, newGroupId + "/groupimage/");

MyMeetUp.Web/Views/Events/Create.cshtml
@model MyMeetUp.Web.Models.Event

@{
    ViewData["Title"] = "Create";
}

<div class="container">
    <div class="row">
        <div class="col">
            <div class="mt-4 mb-2 shadow p-3 bg-white rounded">
                <h2><span><i class="fa fa-file-text"></i></span> Edición Nuevo Evento</h2>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <form asp-controller="Events" asp-action="Create" asp-antiforgery="true" method="post" class="form-horizontal">
                <div class="card">
                    <div class="card-header">Grupo <strong>@ViewData["GroupName"]</strong></div>
                    <div class="card-body">
                        <div class="form-group row">
                            <label class="col-md-3 col-form-label"><strong>Título</strong></label>
                            <div class="col-md-9">
                                <input asp-for="Title" class="form-control" placeholder="Importante pensar en algo con gancho..">
                                <span asp-validation-for="Title" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-3 col-form-label"><strong>Descripción / Detalles</strong></label>
                            <div class="col-md-9">
                                <textarea asp-for="Description" class="form-control" rows="9" placeholder="Describa aquí todos los detalles del evento.."></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-3 col-form-label"><strong>Fecha / Hora</strong></label>
                            <div class="col-md-5">
                                <input asp-for="FechaHora" class="form-control" id="date-input" type="date" placeholder=""><span class="help-block"></span>
                                <span asp-validation-for="FechaHora" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-3 col-form-label"><strong>Dirección</strong></label>
                            <div class="col-md-9">
                                <input asp-for="Address" class="form-control" placeholder=""><span class="help-block"></span>
                                <span asp-validation-for="Address" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-3 col-form-label"><strong>Ciudad</strong></label>
                            <div class="col-md-9">
                                <input asp-for="City" class="form-control" placeholder=""><span class="help-block"></span>
                                <span asp-validation-for="City" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-3 col-form-label"><strong>País</strong></label>
                            <div class="col-md-9">
                                <input asp-for="Country" class="form-control" placeholder=""><span class="help-block"></span>
                                <span asp-validation-for="Country" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-3 col-form-label"><strong>Categoría</strong></label>
                            <div class="col-md-9">
                                <select asp-for="EventCategoryId" class="form-control" asp-items="ViewBag.EventCategoryId"></select>
                            </div>
                        </div>
                        <div>
                            <input asp-for="GroupId" type="hidden" value="@ViewData["GroupId"]" />
                        </div>

                    </div>
                    <div class="card-footer">
                        <button class="btn btn-info float-right"> Crear Evento</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}    
}

MyMeetUp.Web/Views/Events/Details.cshtml
@model MyMeetUp.Web.ViewModels.EventDetailsViewModel
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Información del Evento";
    var userSignedIn = await UserManager.GetUserAsync(User);
    var userId = userSignedIn?.Id;
}

<div class="container">
    <div class="row">
        <div class="col">
            <div class="row">
                <div class="col">
                    <div style="height: 45px">
                        <span><b>@Model.EventInfo.FechaHora.ToString("dddd dd MMM yyyy")</b></span>
                        @if (Model.EventInfo.FechaHora < DateTime.Today) {
                            <span class="badge badge-warning float-right">Evento Finalizado</span>
                        }
                        else if (SignInManager.IsSignedIn(User)) {
                            @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "__EventAttendanceAntiForgeryToken" })) {
                                @Html.AntiForgeryToken()

                                @if (Model.SignedInUserWillAttend) {
                                    <a href="#" class="btn btn-danger float-right" onclick="ManageUserEventAttendance()" id="register-event-button">Liberar Mi Plaza!</a>
                                }
                                else {
                                    <a href="#" class="btn btn-info float-right" onclick="ManageUserEventAttendance()" id="register-event-button">Quiero Asistir!</a>
                                }
                                <input type="hidden" id="userId" value="@userId" />
                                <input type="hidden" id="eventId" value="@Model.EventInfo.Id" />
                            }
                        }
                    </div>
                    <div class="mt-4 mb-2 shadow p-3 bg-white rounded">
                        <h2><span><i class="fa fa-calendar-check-o"></i></span> @Model.EventInfo.Title</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-8">
                    <div class="shadow p-3 bg-white rounded">
                        <p class="card-text">@Model.EventInfo.Description</p>
                    </div>
                </div>
                <div class="col-4">
                    <div class="row">
                        <div class="col">
                            <div class="shadow p-3 bg-white rounded">
                                <a asp-controller="Groups" asp-action="Details" asp-route-id="@Model.EventInfo.GroupId" class="stretched-link"><h5><span><i class="fa fa-group"></i>  @Model.EventInfo.Group.Name</span></h5></a>
                            </div>
                        </div>
                    </div>
                    <div class="mt-1 row">
                        <div class="col">
                            <div class="shadow p-3 bg-white rounded">
                                <p><span><i class="fa fa-clock-o"></i>  @Model.EventInfo.FechaHora.ToString("dd/MM/yyyy hh:mm")</span></p>
                                <p><span><i class="fa fa-map-marker"></i>  @Model.EventInfo.Address</span></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="mt-4 mb-2 shadow p-3 bg-white rounded">
                <h2><span><i class="fa fa-check-circle"></i></span> Asistentes</h2>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col" id="attendees-to-event">
            @await Html.PartialAsync("~/Views/Events/_AttendeesToEvent.cshtml", Model.EventAttendees)
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="mt-4 mb-2 shadow p-3 bg-white rounded">
                <h2><span><i class="fa fa-comments"></i></span> Comentarios</h2>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col" id="event-comments">
            @await Html.PartialAsync("~/Views/Events/_EventComments.cshtml", Model.EventComments)
        </div>
    </div>
    @if (SignInManager.IsSignedIn(User)) {
        <div class="row">
            <div class="col">
                <div class="card mt-2">
                    <div class="card-header"><strong>Nuevo comentario</strong></div>
                    <div class="card-body">
                        @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "__EventCommentAntiForgeryToken" })) {
                            @Html.AntiForgeryToken()
                            <input type="hidden" id="userId" value="@userId" />
                            <input type="hidden" id="eventId" value="@Model.EventInfo.Id" />
                            <div class="row">
                                <div class="col-11">
                                    <textarea class="form-control" id="commentMessage" name="textarea-input" rows="5" placeholder="Escriba aquí.."></textarea>
                                </div>
                                <div class="col-1 alig">
                                    <a href="#" class="btn btn btn-info float-right" onclick="SendComment()" id="send-comment-button">Enviar</a>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    }
</div>

@section Scripts{
    <script type="text/javascript" src="~/js/events.js"></script>
}

MyMeetUp.Web/Views/Events/_AttendeesToEvent.cshtml
@model List<ApplicationUser>

@if (Model != null && Model.Any()) {
    <div class="card-deck">
        @foreach (ApplicationUser attendee in Model) {
            <div class="card mt-2" style="max-width: 20rem; min-width: 20rem;">
                <div class="card-body">
                    <img src="~/img/usuario.png" class="float-left rounded-circle" height="64" width="64">
                    <div class="message">
                        <h5 class="card-title">@attendee.Name</h5>
                        <h6 class="card-subtitle mb-2 text-muted">@attendee.Surname</h6>
                        <p class="card-text">Miembro</p>
                    </div>
                </div>
            </div>
        }
    </div>
}
else {
    <div class="row mt-2">
        <div class="col">
            <div class="card">
                <div class="card-header"><span class="badge badge-warning float-right">Sin asistentes!!</span></div>
                <div class="card-body">No hay asistentes en este evento..</div>
            </div>
        </div>
    </div>
}

MyMeetUp.Web/Views/Events/_EventComments.cshtml
@model List<EventComment>


@if (Model != null && Model.Any()) {
    <div class="comments-container">
        <ul id="comments-list" class="comments-list">
            @foreach (EventComment comment in Model) {
                <li>
                    <div class="comment-main-level">
                        <div class="comment-avatar">
                            <img src="~/img/usuario.png" alt="~/img/usuario.png">
                        </div>
                        <div class="comment-box">
                            <div class="comment-head">
                                <h6 class="comment-name"><a href="#">@($"{comment.ApplicationUser.Name} {comment.ApplicationUser.Surname}")</a></h6>
                                <span>@comment.PublicationDate.ToString("dd/MM/yyyy hh:mm:ss")</span>
                            </div>
                            <div class="comment-content">
                                @($"{comment.Text}")
                            </div>
                        </div>
                    </div>
                </li>
            }
        </ul>
    </div>
}
else {
    <div class="row mt-2">
        <div class="col">
            <div class="card">
                <div class="card-header"><span class="badge badge-warning float-right">Sin comentarios!</span></div>
                <div class="card-body">Sé el primero en comentar..</div>
            </div>
        </div>
    </div>
}