MyMeetUp.Web/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using MyMeetUp.Web.Configuration;
using MyMeetUp.Web.Data;
using MyMeetUp.Web.Models;
using System.Diagnostics;

namespace MyMeetUp.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = RolesData.Administrator)]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IOptions<AppSettings> _appSettings;

        public HomeController(ILogger<HomeController> logger, IOptions<AppSettings> appSettings) {
            _logger = logger;
            _appSettings = appSettings;
        }

        public IActionResult Index() {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MyMeetUp.Web/Areas/Admin/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyMeetUp.Web.Areas.Admin.ViewModels;
using MyMeetUp.Web.Data;
using MyMeetUp.Web.Models;
using MyMeetUp.Web.Models.RoleModel;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace MyMeetUp.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = RolesData.Administrator)]
    public class RoleController : Controller {
        private RoleManager<IdentityRole> _roleManager;
        private UserManager<ApplicationUser> _userManager;

        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager) {
            _roleManager = roleManager;
            _userManager = userManager;
        }


        public IActionResult Index() {
            return View(_roleManager.Roles);
        }

        // GET: Roles/Update/5
        public async Task<IActionResult> Update(string id) {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            List<ApplicationUser> members = new List<ApplicationUser>();
            List<ApplicationUser> nonMembers = new List<ApplicationUser>();
            foreach (ApplicationUser user in _userManager.Users) {
                var list = await _userManager.IsInRoleAsync(user, role.Name) ? members : nonMembers;
                list.Add(user);
            }
            return View(new RoleEdit
            {
                Role = role,
                Members = members,
                NonMembers = nonMembers
            });
        }
        [HttpPost]
        public async Task<IActionResult> Update(RoleModification model) {
            IdentityResult result;
            if (ModelState.IsValid) {
                foreach (string userId in model.AddIds ?? new string[] { }) {
                    ApplicationUser user = await _userManager.FindByIdAsync(userId);
                    if (user != null) {
                        result = await _userManager.AddToRoleAsync(user, model.RoleName);
                        if (!result.Succeeded)
                            Errors(result);
                    }
                }
                foreach (string userId in model.DeleteIds ?? new string[] { }) {
                    ApplicationUser user = await _userManager.FindByIdAsync(userId);
                    if (user != null) {
                        result = await _userManager.RemoveFromRoleAsync(user, model.RoleName);
                        if (!result.Succeeded)
                            Errors(result);
                    }
                }
            }

            if (ModelState.IsValid)
                return RedirectToAction(nameof(Index));
            else
                return await Update(model.RoleId);
        }

        public IActionResult Create() {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(RoleCreateViewModel newRoleModel) 
        {
            if (!ModelState.IsValid)
                return View();

            if (!_roleManager.RoleExistsAsync(newRoleModel.Name).Result) {
                IdentityRole rol = new IdentityRole();
                rol.Name = newRoleModel.Name;
                var roleResult = await _roleManager.CreateAsync(rol);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(string rolename) 
        {
            var role = await _roleManager.FindByNameAsync(rolename);
            if (role != null)
                await _roleManager.DeleteAsync(role);
            
            return RedirectToAction("Index");
        }

        private void Errors(IdentityResult result) {
            foreach (IdentityError error in result.Errors)
                ModelState.AddModelError("", error.Description);
        }
    }
}

MyMeetUp.Web/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using MyMeetUp.Web.Data;
using MyMeetUp.Web.Models;
using MyMeetUp.Web.Services.Interfaces;
using MyMeetUp.Web.ViewModels;
using Microsoft.ApplicationInsights;

namespace MyMeetUp.Web.Controllers
{
    public class EventsController : Controller
    {
        private const string WILL_ATTEND = "I WILL ATTEND";
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger _logger;
        private readonly IQueueService _eventQueueService;
        private TelemetryClient _telemetryClient;

        public EventsController(ApplicationDbContext context, 
                                UserManager<ApplicationUser> userManager, 
                                ILogger<EventsController> logger,
                                IQueueService eventQueueService,
                                TelemetryClient telemetry)
        {
            _context = context;
            _userManager = userManager;
            _logger = logger;
            _eventQueueService = eventQueueService;
            _telemetryClient = telemetry;
        }

        // GET: Events/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) {
                _logger.LogWarning($"Detalles del Evento {id} no encontrados");
                return NotFound();
            }
                
            //Event Info
            var eventSelected = await _context.Events
                .Include(ec => ec.EventCategory)
                .Include(g => g.Group)
                .FirstOrDefaultAsync(m => m.Id == id);
            
            if (eventSelected == null) {
                _logger.LogError($"Consulta de base de datos NOK sobre el Evento {id}. No encontrado.");
                return NotFound();
            }

            //SignedIn User Info
            bool signedInUserWillAttend = false;
            var userId = User.FindFirst(ClaimTypes.NameIdentifier);
            if(userId != null) {
                signedInUserWillAttend = _context.EventAttendances.Where(ea => ((ea.ApplicationUserId == userId.Value) && (ea.EventId == eventSelected.Id))).Any();
            }


            //List of Users Will Attend the Event
            List<ApplicationUser> eventAttendeesList = await _context.EventAttendances
                                                                    .Include(ea => ea.ApplicationUser)
                                                                    .Where(ea => ea.EventId == id)
                                                                    .Select(ea => ea.ApplicationUser)
                                                                    .ToListAsync();

            //List of Comments associated to the event
            List<EventComment> eventComments = await _context.EventComments
                                                    .Include(ec => ec.ApplicationUser)
                                                    .Where(ec => ec.EventId == id)
                                                    .ToListAsync();

            EventDetailsViewModel eventInfo = new EventDetailsViewModel { 
                EventInfo = eventSelected,
                SignedInUserWillAttend = signedInUserWillAttend,
                EventAttendees = eventAttendeesList,
                EventComments = eventComments
            };

            var dictionay = new Dictionary<string, string>();
            dictionay.Add("Event Details", eventSelected.Title);
            _telemetryClient.TrackEvent("UserInteraction", dictionay);
            
            return View(eventInfo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddNewAttendee(string userId, int eventId) 
        {
            ApplicationUser user = await _userManager.FindByIdAsync(userId);
            Event eventSelected = await _context.Events.FirstOrDefaultAsync(e => e.Id == eventId);
            EventAttendanceState eventAttendaceState = await _context.EventAttendanceStates.Where(ea => ea.State == WILL_ATTEND).FirstOrDefaultAsync();
            if ((user is null) || (eventSelected is null))
                return Ok(new { success = false });

            EventAttendance eventAttendance = new EventAttendance { 
                ApplicationUser = user,
                ApplicationUserId = user.Id,
                Event = eventSelected,
                EventId = eventSelected.Id,
                EventAttendanceState = eventAttendaceState,
                EventAttendanceStateId = eventAttendaceState.Id
            };

            try {
                if (_context.EventAttendances.Any(ea => ((ea.ApplicationUserId == userId) && (ea.EventId == eventSelected.Id)))) {
                        EventAttendance actualEventAttendace = await _context.EventAttendances.Where(ea => ((ea.ApplicationUserId == userId) && (ea.EventId == eventSelected.Id))).AsNoTracking().FirstOrDefaultAsync();
                    eventAttendance.Id = actualEventAttendace.Id;
                    _context.EventAttendances.Update(eventAttendance);
                }
                else {
                    _context.EventAttendances.Add(eventAttendance);
                }
                await _context.SaveChangesAsync();
                _logger.LogInformation($"Usuario {userId} inscrito en evento {eventId}.");
            } catch (Exception e) {
                _logger.LogCritical($"EXCEPCIÓN: {e.Message}");
                return Ok(new { success = false });
            }

            var dictionay = new Dictionary<string, string>();
            dictionay.Add("Event New Attendee", eventAttendance.ApplicationUser.Name);
            _telemetryClient.TrackEvent("UserInteraction", dictionay);

            return Ok(new { success = true });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LeaveMySeat(string userId, int eventId) 
        {
            try {

                EventAttendance e = await _context.EventAttendances.FirstOrDefaultAsync(ea => ea.EventId == eventId && ea.ApplicationUserId == userId);
                _context.Remove(e);
                await _context.SaveChangesAsync();
            } catch (Exception e) {
                _logger.LogCritical($"EXCEPCIÓN: {e.Message}");
                return Json(new { success = false });
            }

            var dictionay = new Dictionary<string, string>();
            dictionay.Add("Event Leave My Seat", $"userId : {userId}");
            _telemetryClient.TrackEvent("UserInteraction", dictionay);

            return Json(new { success = true });
        }

        //GET: Events/AttendeesList/5
        [HttpGet]
        public async Task<PartialViewResult> AttendeesList(int eventId) 
        {
            if (eventId != 0) {
                var attendeesToEvent = await _context.EventAttendances.Include(ea => ea.ApplicationUser).Where(ea => ea.EventId == eventId).ToListAsync();
                List<ApplicationUser> attendeesList = new List<ApplicationUser>();
                foreach (EventAttendance eventAttendance in attendeesToEvent) {
                    attendeesList.Add(eventAttendance.ApplicationUser);
                }
                return PartialView("_AttendeesToEvent", attendeesList);
            }
            _logger.LogError($"Lista de asistentes al evento {eventId} no encontrada.");
            return null;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<PartialViewResult> NewComment(string userId, int eventId, string commentMessage) 
        {
            if (userId == "" || eventId == 0 || commentMessage == "")
                return null;

            EventComment newEventComment = new EventComment {
                ApplicationUserId = userId,
                EventId = eventId,
                Text = commentMessage,
                PublicationDate = DateTime.Now,
                ParentEventCommentId = null
            };

            try {
                _context.EventComments.Add(newEventComment);
                await _context.SaveChangesAsync();

                var dictionay = new Dictionary<string, string>();
                dictionay.Add("Event New Comment", $"eventId: {eventId}");
                _telemetryClient.TrackEvent("UserInteraction", dictionay);
            } 
            catch (Exception e) {
                _logger.LogCritical($"EXCEPCION en NewComment: {e.Message}");
                return null;
            }

            List<EventComment> comments = await _context.EventComments
                                                        .Include(c => c.ApplicationUser)
                                                        .Where(c => c.EventId == eventId)
                                                        .ToListAsync();
            return PartialView("_EventComments", comments);
        }

        // GET: Events/Create
        public IActionResult Create(int idGroup) {
            ViewData["EventCategoryId"] = new SelectList(_context.EventCategories, "Id", "Name");
            ViewData["GroupId"] = idGroup;
            ViewData["GroupName"] = _context.Groups.FirstOrDefaultAsync(g => g.Id == idGroup).Result.Name;
            return View();
        }

        // POST: Events/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,Description,Address,City,Country,FechaHora,GroupId,EventCategoryId,Id")] Event groupEvent) {
            if (!ModelState.IsValid) {

MyMeetUp.Web/Areas/Admin/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Area Administración";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">Área Administración</li>
    </ol>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="card-deck">
            <div class="card text-white bg-dark mb-3">
                <div class="card-header">GRUPOS</div>
                <div class="card-body">
                    <h5 class="card-title">Administración de grupos</h5>
                    <p class="card-text">Configuración de todas las funcionalidades relacionadas con la entidad de Grupo</p>
                    <a asp-area="Admin" asp-controller="Groups" asp-action="Index" class="btn btn-primary">Acceder</a>
                </div>
            </div>
            <div class="card text-white bg-dark mb-3">
                <div class="card-header">CATEGORÍAS DE GRUPOS</div>
                <div class="card-body">
                    <h5 class="card-title">Administración de categorías de grupo</h5>
                    <p class="card-text">Crear, eliminar y actualizar las diferentes categorías de grupos existentes</p>
                    <a asp-area="Admin" asp-controller="GroupCategories" asp-action="Index" class="btn btn-primary">Acceder</a>
                </div>
            </div>
            <div class="card text-white bg-dark mb-3">
                <div class="card-header">PERFILES DE MIEMBROS EN UN GRUPO</div>
                <div class="card-body">
                    <h5 class="card-title">Administración de perfiles de miembros de grupo</h5>
                    <p class="card-text">Crear, eliminar y actualizar las diferentes perfiles que puede tener un miembro de un grupo</p>
                    <a asp-area="Admin" asp-controller="GroupMemberProfiles" asp-action="Index" class="btn btn-primary">Acceder</a>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="card-deck">
            <div class="card text-white bg-dark mb-3">
                <div class="card-header">EVENTOS</div>
                <div class="card-body">
                    <h5 class="card-title">Administración de eventos</h5>
                    <p class="card-text">Configuración de todas las funcionalidades relacionadas con la entidad de Evento</p>
                    <a asp-area="Admin" asp-controller="Events" asp-action="Index" class="btn btn-primary">Acceder</a>
                </div>
            </div>
            <div class="card text-white bg-dark mb-3">
                <div class="card-header">CATEGORÍAS DE EVENTOS</div>
                <div class="card-body">
                    <h5 class="card-title">Administración de categorías de evento</h5>
                    <p class="card-text">Crear, eliminar y actualizar las diferentes categorías de eventos existentes</p>
                    <a asp-area="Admin" asp-controller="EventCategories" asp-action="Index" class="btn btn-primary">Acceder</a>
                </div>
            </div>
            <div class="card text-white bg-dark mb-3">
                <div class="card-header">ESTADOS ASISTENCIA EVENTOS</div>
                <div class="card-body">
                    <h5 class="card-title">Administración de estados de asistencias a eventos</h5>
                    <p class="card-text">Crear, eliminar y actualizar las estados de asistencia de un miembro en un grupo</p>
                    <a asp-area="Admin" asp-controller="EventAttendanceStates" asp-action="Index" class="btn btn-primary">Acceder</a>
                </div>
            </div>
            <div class="card text-white bg-dark mb-3">
                <div class="card-header">COMENTARIOS DE EVENTOS</div>
                <div class="card-body">
                    <h5 class="card-title">Administración de los comentarios de evento</h5>
                    <p class="card-text">Crear, eliminar y actualizar los diferentes comentarios asociados a un envento</p>
                    <a asp-area="Admin" asp-controller="EventComments" asp-action="Index" class="btn btn-primary">Acceder</a>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="card-deck">
            <div class="card text-white bg-dark mb-3">
                <div class="card-header">USUARIOS</div>
                <div class="card-body">
                    <h5 class="card-title">Administración de usuarios registrados</h5>
                    <p class="card-text">Crear, eliminar y actualizar los diferentes usuarios registrados en el sistema</p>
                    <a asp-area="Admin" asp-controller="ApplicationUsers" asp-action="Index" class="btn btn-primary">Acceder</a>
                </div>
            </div>
            <div class="card text-white bg-dark mb-3">
                <div class="card-header">ROLES</div>
                <div class="card-body">
                    <h5 class="card-title">Administración de los roles de la aplicación</h5>
                    <p class="card-text">Crear, eliminar y actualizar los diferentes roles que participan en la aplicación</p>
                    <a asp-area="Admin" asp-controller="Role" asp-action="Index" class="btn btn-primary">Acceder</a>
                </div>
            </div>
        </div>
    </div>
</div>